### ISSUE TITLE
Change number of rows and columns displayed

### ISSUE THREAD

**Issue by kreativmind** [vikgor/portfolio#5]
I would like to be able to change the existing 6 images to 9 or 12. Is that possible?

**Comment by vikgor** [comment]
Hello! Sorry for the late response, it is possible, you can edit that in the Settings -> Advanced -> Items per page, change that to whatever suits you best.

**Comment by kreativmind** [comment]
Actually, I know about that but it only goes up to 8 or All Content I was thinking maybe there was a line of code in your theme that could control the pagination and image count. Thanks anyway.

**Comment by vikgor** [comment]
It turns out you can change the number of posts on the main page, but it's not in the theme code, it's in the Bludit kernel, in this file:
_/bludit/bl-kernel/admin/views/settings.php_
Line 87 (at this moment, v. 3.10.0):

`'options'=>array('1'=>'1','2'=>'2','3'=>'3','4'=>'4','5'=>'5','6'=>'6','7'=>'7','8'=>'8', '-1'=>$L->g('All content')),`

Just add `'number'=>'number',` it will look like this:

`'options'=>array('1'=>'1','2'=>'2','3'=>'3','4'=>'4','5'=>'5','6'=>'6','7'=>'7','8'=>'8','9'=>'9','10'=>'10','12'=>'12','22'=>'22','-1'=>$L->g('All content')),`

But the next time you update Bludit this will probably go back to default unless we try to push this change or this file remains untouched and not updated. Anyway hope this helps you.

**Comment by kreativmind** [comment]
It will go back. I've already tried that before and when we update, naturally it gets overwritten.
